### ISSUE TITLE
TODO toward releasing MAGELLAN RAG

### ISSUE THREAD

**Issue by mrkn** [xica/res-chatbot#4]
- [ ] Integrate with report-rag-api
- [ ] Implement the testing mode in report-rag-api with real API responses
- [ ] Writing regular case integration test
- [ ] Writing error case integration test
